services:
  frontend:
    build:
      context: ./synthetic-forest-generator-ui
      dockerfile: Dockerfile
    container_name: ui-app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
    stdin_open: true
    tty: true
    networks:
      - appnet

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: generator-db
    ports:
      - "5432:5432"
    networks:
      - appnet

networks:
  appnet:
